[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gnumake", "gcc"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm rebuild better-sqlite3"]

[start]
cmd = "node index.js"
